let questions_list* = """
[
  "I am a sympathetic person.",
  "I often use words and phrases from movies and television in conversations.",
  "I am often surprised when others tell me I have been rude.",
  "Sometimes I talk to loudly or too softly and I am not aware of it.",
  "I often don't know how to act in social situations.",
  "I can \"put myself in other people's shoes.\"",
  "I have a hard time figuring out what some phrases mean, like \"you are the apple of my eye\".",
  "I only like to talk to people who share my special interests.",
  "I focus on details rather than the overall idea.",
  "I always notice how food feels in my mouth. This is more important to me than how it tastes.",
  "I miss my best friends or family when we are apart for a long time.",
  "Sometimes I offend others by saying what I am thinking, even if I don't mean to.",
  "I only like to think and talk about a few things that interest me.",
  "I'd rather go out to eat in a restaurant by myself than with someone I know.",
  "I cannot imagine what it would be like to be someone else.",
  "I have been told that I am clumsy or uncoordinated.",
  "Others consider me odd or different.",
  "I understand when friends need to be comforted.",
  "I am very sensitive to the way my clothes feel when I touch them. How they feel is more important to me than how they look.",
  "I like to copy the way certain people speak and act. It helps me appear more normal.",
  "It can be very intimidating for me to talk to more than one person at a time.",
  "I have to \"act normal\" to please other people and make them like me.",
  "Meeting new people is usually easy for me.",
  "I get highly confused when someone interrupts me when I am talking about something I am very interested in.",
  "It is difficult for me to understand how other people are feeling when we are talking.",
  "I like having a converstation with several people, for instance around a dinner table, at school or at work.",
  "I take things too literally, so often I miss what people are trying to say.",
  "It is very difficult for me to understand when someone is embarrased or jealous.",
  "Some ordinary textures that do not bother others feel very offensive when they touch my skin.",
  "I get extremely upset when the way I like to do things is suddenly changed.",
  "I have never wanted or needed to have what other people call an \"intimate relationship\".",
  "It is difficult for me to start and stop a conversation. I need to keep going until I am finished.",
  "I speak with a normal rhythm.",
  "The same sound, color or texture can suddenly change from very sensitive to very dull.",
  "The phrase \"I've got you under my skin\" makes me very uncomfortable.",
  "Sometimes the sound of a word or high-pitched noise can be painful to my ears.",
  "I am an understanding type of person.",
  "I do not connect with characters in movies and cannot feel what they feel.",
  "I cannot tell what someone is flirting with me.",
  "I can see in my mind in exact detail things that I am interested in.",
  "I keep lists of things that interest me, even when they have no practical use (for example sports statistics, train schedules, calendar dates, historical facts and dates).",
  "When I feel overwhelmed by my senses, I have to isolate myself to shut them down.",
  "I like to talk things over with my friends.",
  "I cannot tell if someone is interested or bored with what I am saying.",
  "It can be very hard to read someone's face, hand and body movements when they are talking.",
  "The same thing (like clothes or temperature) can feel very different to me at different times.",
  "I feel very comfortable with dating or being in social situations with others.",
  "I try to be as helpful as I can when other people tell me their personal problems.",
  "I have been told that I have an unusual voice (for example flat, monotone, childish, or high-pitched).",
  "Sometimes a thought or a subject gets stuck in my mind and I have to talk about it even if no one is interested.",
  "I do certain things with my hands over and over again (like flapping, twirling sticks or strings, waving things by my eyes).",
  "I have never been interested in what most of the people I know consider interesting.",
  "I am considered a compassionate type of person.",
  "I get along with other people by following a set of specific rules that help me look normal.",
  "It is very difficult for me to work and function in groups.",
  "When I am talking to someone, it is hard to change the subject. If the other persona does so, I can get very upset and confused.",
  "Sometimes I have to cover my ears to block out painful noises (like vacuum cleaners or people talking too much or too loudly).",
  "I can chat and make small talk with people.",
  "Sometimes things that should feel painful are not (for instance when I hurt myself or burn my hand on a stove)",
  "When talking to someone, I have a hard time telling when it is my turn to talk or listen.",
  "I am considerd a loner by those who know me best.",
  "I usually speak in a normal tone.",
  "I like things to be exactly the same day after day and even small changes in my routines upset me.",
  "How to make friends and socialize is a mystery to me.",
  "It calms me to spin around or to rock in a chair when I am feeling stressed.",
  "The phrase, \"He wears his heart on his sleeve.\" does not make sense to me.",
  "If I am in a place where there are many smells, textures to feel, noises or bright lights, I feel anxious or frightened.",
  "I can tell when someone says one thing but means something else.",
  "I like to be by myself as much as I can.",
  "I keep my thoughts stacked in my memory like they are on filing cards, and I pick out the ones I need by looking through the stack and finding the right one (or another unique way).",
  "The same sound sometimes seems very loud or very soft, even though I know it has not changed.",
  "I enjoy spending time eating and talking with my family and friends.",
  "I can't tolerate things I dislike (like smells, textures, sounds or colors).",
  "I don't like to be hugged or held.",
  "When I go somewhere, I have to follow a familiar route or I can get very confused and upset.",
  "It is difficult to figure out what other people expect of me.",
  "I like to have close friends.",
  "People tell me that I give too much detail.",
  "I am often told that I ask embarrasing questions.",
  "I tend to point out other people's mistakes."
]
"""
